AWSTemplateFormatVersion: "2010-09-09"
Description: this template describes nadia and linda ec2 written in yaml
Parameters:
  InstanceType:
      Description: WebServer EC2 instance type
      Type: String
      Default: t2.micro
      AllowedValues:
      - t1.micro
      - t2.nano
      - t2.micro
  VolumeSize:
    Description: EBS Volume size
    Type: Number
    Default: 8
    MinValue: 8
    MaxValue: 100
    ConstraintDescription: must be a number between 8 to 100 Gb
  
  AMIID:
    Description: The EC2 AMI id
    Type: String  
    Default: ami-02d1e544b84bf7502
    ConstraintDescription: Must be a valid AMI based on the region
  
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.  

  SecurityGroupPorts:
    Description: Simple Description of a Number Parameter, with MinValue and MaxValue
    Type: Number
    AllowedValues: 
      - 80
      - 443
      - 22   

  VPCId:
    Description: VPC to create the security group into
    Type: AWS::EC2::VPC::Id

  ApplicationName:
    Description: The application name
    Type: String

Resources: 
  LindaEC2: 
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: 
        Ref: AMIID
      KeyName: 
        Ref: KeyName
      InstanceType: 
        Ref: InstanceType
      BlockDeviceMappings: 
        -
          DeviceName: /dev/xvda
          Ebs: 
            VolumeType: gp2
            DeleteOnTermination: true
            VolumeSize: 
              Ref: VolumeSize
      Tags: 
        - Key: Name
          Value: Fru
        - Key: Env
          Value: Dev
        - Key: CreatedBy
          Value: Me

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub Security group for ${ApplicationName}
      SecurityGroupIngress:
        - CidrIp: "10.0.0.0/25"
          FromPort: !Ref SecurityGroupPorts
          ToPort: !Ref SecurityGroupPorts
          IpProtocol: tcp
          Description: SSH for Engineering department
      VpcId: !Ref VPCId

  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: bucfru12111        